// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-cli.proto

package com.y4d.git.cli;

public final class GitCliProto {
    private GitCliProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface GitCliOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.y4d.git.cli.GitCli)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string host = 1;</code>
         *
         * @return The host.
         */
        java.lang.String getHost();

        /**
         * <code>string host = 1;</code>
         *
         * @return The bytes for host.
         */
        com.google.protobuf.ByteString
        getHostBytes();

        /**
         * <code>int32 port = 2;</code>
         *
         * @return The port.
         */
        int getPort();

        /**
         * <code>string cmd = 3;</code>
         *
         * @return The cmd.
         */
        java.lang.String getCmd();

        /**
         * <code>string cmd = 3;</code>
         *
         * @return The bytes for cmd.
         */
        com.google.protobuf.ByteString
        getCmdBytes();

        /**
         * <code>string path = 4;</code>
         *
         * @return The path.
         */
        java.lang.String getPath();

        /**
         * <code>string path = 4;</code>
         *
         * @return The bytes for path.
         */
        com.google.protobuf.ByteString
        getPathBytes();

        /**
         * <code>string user_id = 5;</code>
         *
         * @return The userId.
         */
        java.lang.String getUserId();

        /**
         * <code>string user_id = 5;</code>
         *
         * @return The bytes for userId.
         */
        com.google.protobuf.ByteString
        getUserIdBytes();

        /**
         * <code>string user_ip = 6;</code>
         *
         * @return The userIp.
         */
        java.lang.String getUserIp();

        /**
         * <code>string user_ip = 6;</code>
         *
         * @return The bytes for userIp.
         */
        com.google.protobuf.ByteString
        getUserIpBytes();

        /**
         * <code>string username = 7;</code>
         *
         * @return The username.
         */
        java.lang.String getUsername();

        /**
         * <code>string username = 7;</code>
         *
         * @return The bytes for username.
         */
        com.google.protobuf.ByteString
        getUsernameBytes();
    }

    /**
     * Protobuf type {@code com.y4d.git.cli.GitCli}
     */
    public static final class GitCli extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.y4d.git.cli.GitCli)
            GitCliOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use GitCli.newBuilder() to construct.
        private GitCli(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private GitCli() {
            host_ = "";
            cmd_ = "";
            path_ = "";
            userId_ = "";
            userIp_ = "";
            username_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new GitCli();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.y4d.git.cli.GitCliProto.internal_static_com_y4d_git_cli_GitCli_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.y4d.git.cli.GitCliProto.internal_static_com_y4d_git_cli_GitCli_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.y4d.git.cli.GitCliProto.GitCli.class, com.y4d.git.cli.GitCliProto.GitCli.Builder.class);
        }

        public static final int HOST_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object host_ = "";

        /**
         * <code>string host = 1;</code>
         *
         * @return The host.
         */
        @java.lang.Override
        public java.lang.String getHost() {
            java.lang.Object ref = host_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                host_ = s;
                return s;
            }
        }

        /**
         * <code>string host = 1;</code>
         *
         * @return The bytes for host.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getHostBytes() {
            java.lang.Object ref = host_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                host_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PORT_FIELD_NUMBER = 2;
        private int port_ = 0;

        /**
         * <code>int32 port = 2;</code>
         *
         * @return The port.
         */
        @java.lang.Override
        public int getPort() {
            return port_;
        }

        public static final int CMD_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object cmd_ = "";

        /**
         * <code>string cmd = 3;</code>
         *
         * @return The cmd.
         */
        @java.lang.Override
        public java.lang.String getCmd() {
            java.lang.Object ref = cmd_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                cmd_ = s;
                return s;
            }
        }

        /**
         * <code>string cmd = 3;</code>
         *
         * @return The bytes for cmd.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getCmdBytes() {
            java.lang.Object ref = cmd_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                cmd_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PATH_FIELD_NUMBER = 4;
        @SuppressWarnings("serial")
        private volatile java.lang.Object path_ = "";

        /**
         * <code>string path = 4;</code>
         *
         * @return The path.
         */
        @java.lang.Override
        public java.lang.String getPath() {
            java.lang.Object ref = path_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                path_ = s;
                return s;
            }
        }

        /**
         * <code>string path = 4;</code>
         *
         * @return The bytes for path.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getPathBytes() {
            java.lang.Object ref = path_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                path_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int USER_ID_FIELD_NUMBER = 5;
        @SuppressWarnings("serial")
        private volatile java.lang.Object userId_ = "";

        /**
         * <code>string user_id = 5;</code>
         *
         * @return The userId.
         */
        @java.lang.Override
        public java.lang.String getUserId() {
            java.lang.Object ref = userId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                userId_ = s;
                return s;
            }
        }

        /**
         * <code>string user_id = 5;</code>
         *
         * @return The bytes for userId.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUserIdBytes() {
            java.lang.Object ref = userId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int USER_IP_FIELD_NUMBER = 6;
        @SuppressWarnings("serial")
        private volatile java.lang.Object userIp_ = "";

        /**
         * <code>string user_ip = 6;</code>
         *
         * @return The userIp.
         */
        @java.lang.Override
        public java.lang.String getUserIp() {
            java.lang.Object ref = userIp_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                userIp_ = s;
                return s;
            }
        }

        /**
         * <code>string user_ip = 6;</code>
         *
         * @return The bytes for userIp.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUserIpBytes() {
            java.lang.Object ref = userIp_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userIp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int USERNAME_FIELD_NUMBER = 7;
        @SuppressWarnings("serial")
        private volatile java.lang.Object username_ = "";

        /**
         * <code>string username = 7;</code>
         *
         * @return The username.
         */
        @java.lang.Override
        public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                username_ = s;
                return s;
            }
        }

        /**
         * <code>string username = 7;</code>
         *
         * @return The bytes for username.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
            }
            if (port_ != 0) {
                output.writeInt32(2, port_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmd_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, path_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userId_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userIp_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userIp_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, username_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
            }
            if (port_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, port_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cmd_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmd_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, path_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userId_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userIp_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userIp_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, username_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.y4d.git.cli.GitCliProto.GitCli)) {
                return super.equals(obj);
            }
            com.y4d.git.cli.GitCliProto.GitCli other = (com.y4d.git.cli.GitCliProto.GitCli) obj;

            if (!getHost()
                    .equals(other.getHost())) return false;
            if (getPort()
                    != other.getPort()) return false;
            if (!getCmd()
                    .equals(other.getCmd())) return false;
            if (!getPath()
                    .equals(other.getPath())) return false;
            if (!getUserId()
                    .equals(other.getUserId())) return false;
            if (!getUserIp()
                    .equals(other.getUserIp())) return false;
            if (!getUsername()
                    .equals(other.getUsername())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + HOST_FIELD_NUMBER;
            hash = (53 * hash) + getHost().hashCode();
            hash = (37 * hash) + PORT_FIELD_NUMBER;
            hash = (53 * hash) + getPort();
            hash = (37 * hash) + CMD_FIELD_NUMBER;
            hash = (53 * hash) + getCmd().hashCode();
            hash = (37 * hash) + PATH_FIELD_NUMBER;
            hash = (53 * hash) + getPath().hashCode();
            hash = (37 * hash) + USER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getUserId().hashCode();
            hash = (37 * hash) + USER_IP_FIELD_NUMBER;
            hash = (53 * hash) + getUserIp().hashCode();
            hash = (37 * hash) + USERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getUsername().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.y4d.git.cli.GitCliProto.GitCli parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.y4d.git.cli.GitCliProto.GitCli prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.y4d.git.cli.GitCli}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.y4d.git.cli.GitCli)
                com.y4d.git.cli.GitCliProto.GitCliOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.y4d.git.cli.GitCliProto.internal_static_com_y4d_git_cli_GitCli_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.y4d.git.cli.GitCliProto.internal_static_com_y4d_git_cli_GitCli_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.y4d.git.cli.GitCliProto.GitCli.class, com.y4d.git.cli.GitCliProto.GitCli.Builder.class);
            }

            // Construct using com.y4d.git.cli.GitCliProto.GitCli.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                host_ = "";
                port_ = 0;
                cmd_ = "";
                path_ = "";
                userId_ = "";
                userIp_ = "";
                username_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.y4d.git.cli.GitCliProto.internal_static_com_y4d_git_cli_GitCli_descriptor;
            }

            @java.lang.Override
            public com.y4d.git.cli.GitCliProto.GitCli getDefaultInstanceForType() {
                return com.y4d.git.cli.GitCliProto.GitCli.getDefaultInstance();
            }

            @java.lang.Override
            public com.y4d.git.cli.GitCliProto.GitCli build() {
                com.y4d.git.cli.GitCliProto.GitCli result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.y4d.git.cli.GitCliProto.GitCli buildPartial() {
                com.y4d.git.cli.GitCliProto.GitCli result = new com.y4d.git.cli.GitCliProto.GitCli(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.y4d.git.cli.GitCliProto.GitCli result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.host_ = host_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.port_ = port_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.cmd_ = cmd_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.path_ = path_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.userId_ = userId_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.userIp_ = userIp_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.username_ = username_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.y4d.git.cli.GitCliProto.GitCli) {
                    return mergeFrom((com.y4d.git.cli.GitCliProto.GitCli) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.y4d.git.cli.GitCliProto.GitCli other) {
                if (other == com.y4d.git.cli.GitCliProto.GitCli.getDefaultInstance()) return this;
                if (!other.getHost().isEmpty()) {
                    host_ = other.host_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.getPort() != 0) {
                    setPort(other.getPort());
                }
                if (!other.getCmd().isEmpty()) {
                    cmd_ = other.cmd_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (!other.getPath().isEmpty()) {
                    path_ = other.path_;
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                if (!other.getUserId().isEmpty()) {
                    userId_ = other.userId_;
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                if (!other.getUserIp().isEmpty()) {
                    userIp_ = other.userIp_;
                    bitField0_ |= 0x00000020;
                    onChanged();
                }
                if (!other.getUsername().isEmpty()) {
                    username_ = other.username_;
                    bitField0_ |= 0x00000040;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                host_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 16: {
                                port_ = input.readInt32();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 26: {
                                cmd_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                path_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 42: {
                                userId_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 50: {
                                userIp_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 50
                            case 58: {
                                username_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 58
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object host_ = "";

            /**
             * <code>string host = 1;</code>
             *
             * @return The host.
             */
            public java.lang.String getHost() {
                java.lang.Object ref = host_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    host_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string host = 1;</code>
             *
             * @return The bytes for host.
             */
            public com.google.protobuf.ByteString
            getHostBytes() {
                java.lang.Object ref = host_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    host_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string host = 1;</code>
             *
             * @param value The host to set.
             * @return This builder for chaining.
             */
            public Builder setHost(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                host_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string host = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearHost() {
                host_ = getDefaultInstance().getHost();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>string host = 1;</code>
             *
             * @param value The bytes for host to set.
             * @return This builder for chaining.
             */
            public Builder setHostBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                host_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private int port_;

            /**
             * <code>int32 port = 2;</code>
             *
             * @return The port.
             */
            @java.lang.Override
            public int getPort() {
                return port_;
            }

            /**
             * <code>int32 port = 2;</code>
             *
             * @param value The port to set.
             * @return This builder for chaining.
             */
            public Builder setPort(int value) {

                port_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>int32 port = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPort() {
                bitField0_ = (bitField0_ & ~0x00000002);
                port_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object cmd_ = "";

            /**
             * <code>string cmd = 3;</code>
             *
             * @return The cmd.
             */
            public java.lang.String getCmd() {
                java.lang.Object ref = cmd_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    cmd_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string cmd = 3;</code>
             *
             * @return The bytes for cmd.
             */
            public com.google.protobuf.ByteString
            getCmdBytes() {
                java.lang.Object ref = cmd_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    cmd_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string cmd = 3;</code>
             *
             * @param value The cmd to set.
             * @return This builder for chaining.
             */
            public Builder setCmd(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                cmd_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>string cmd = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCmd() {
                cmd_ = getDefaultInstance().getCmd();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>string cmd = 3;</code>
             *
             * @param value The bytes for cmd to set.
             * @return This builder for chaining.
             */
            public Builder setCmdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                cmd_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private java.lang.Object path_ = "";

            /**
             * <code>string path = 4;</code>
             *
             * @return The path.
             */
            public java.lang.String getPath() {
                java.lang.Object ref = path_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    path_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string path = 4;</code>
             *
             * @return The bytes for path.
             */
            public com.google.protobuf.ByteString
            getPathBytes() {
                java.lang.Object ref = path_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    path_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string path = 4;</code>
             *
             * @param value The path to set.
             * @return This builder for chaining.
             */
            public Builder setPath(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                path_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>string path = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPath() {
                path_ = getDefaultInstance().getPath();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <code>string path = 4;</code>
             *
             * @param value The bytes for path to set.
             * @return This builder for chaining.
             */
            public Builder setPathBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                path_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            private java.lang.Object userId_ = "";

            /**
             * <code>string user_id = 5;</code>
             *
             * @return The userId.
             */
            public java.lang.String getUserId() {
                java.lang.Object ref = userId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    userId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string user_id = 5;</code>
             *
             * @return The bytes for userId.
             */
            public com.google.protobuf.ByteString
            getUserIdBytes() {
                java.lang.Object ref = userId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    userId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string user_id = 5;</code>
             *
             * @param value The userId to set.
             * @return This builder for chaining.
             */
            public Builder setUserId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userId_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>string user_id = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserId() {
                userId_ = getDefaultInstance().getUserId();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            /**
             * <code>string user_id = 5;</code>
             *
             * @param value The bytes for userId to set.
             * @return This builder for chaining.
             */
            public Builder setUserIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                userId_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            private java.lang.Object userIp_ = "";

            /**
             * <code>string user_ip = 6;</code>
             *
             * @return The userIp.
             */
            public java.lang.String getUserIp() {
                java.lang.Object ref = userIp_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    userIp_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string user_ip = 6;</code>
             *
             * @return The bytes for userIp.
             */
            public com.google.protobuf.ByteString
            getUserIpBytes() {
                java.lang.Object ref = userIp_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    userIp_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string user_ip = 6;</code>
             *
             * @param value The userIp to set.
             * @return This builder for chaining.
             */
            public Builder setUserIp(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userIp_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>string user_ip = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserIp() {
                userIp_ = getDefaultInstance().getUserIp();
                bitField0_ = (bitField0_ & ~0x00000020);
                onChanged();
                return this;
            }

            /**
             * <code>string user_ip = 6;</code>
             *
             * @param value The bytes for userIp to set.
             * @return This builder for chaining.
             */
            public Builder setUserIpBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                userIp_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            private java.lang.Object username_ = "";

            /**
             * <code>string username = 7;</code>
             *
             * @return The username.
             */
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string username = 7;</code>
             *
             * @return The bytes for username.
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string username = 7;</code>
             *
             * @param value The username to set.
             * @return This builder for chaining.
             */
            public Builder setUsername(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                username_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUsername() {
                username_ = getDefaultInstance().getUsername();
                bitField0_ = (bitField0_ & ~0x00000040);
                onChanged();
                return this;
            }

            /**
             * <code>string username = 7;</code>
             *
             * @param value The bytes for username to set.
             * @return This builder for chaining.
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                username_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.y4d.git.cli.GitCli)
        }

        // @@protoc_insertion_point(class_scope:com.y4d.git.cli.GitCli)
        private static final com.y4d.git.cli.GitCliProto.GitCli DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.y4d.git.cli.GitCliProto.GitCli();
        }

        public static com.y4d.git.cli.GitCliProto.GitCli getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<GitCli>
                PARSER = new com.google.protobuf.AbstractParser<GitCli>() {
            @java.lang.Override
            public GitCli parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<GitCli> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<GitCli> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.y4d.git.cli.GitCliProto.GitCli getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_y4d_git_cli_GitCli_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_y4d_git_cli_GitCli_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rgit-cli.proto\022\017com.y4d.git.cli\"s\n\006GitC" +
                        "li\022\014\n\004host\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\013\n\003cmd\030\003 " +
                        "\001(\t\022\014\n\004path\030\004 \001(\t\022\017\n\007user_id\030\005 \001(\t\022\017\n\007us" +
                        "er_ip\030\006 \001(\t\022\020\n\010username\030\007 \001(\tB\036\n\017com.y4d" +
                        ".git.cliB\013GitCliProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_y4d_git_cli_GitCli_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_y4d_git_cli_GitCli_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_y4d_git_cli_GitCli_descriptor,
                new java.lang.String[]{"Host", "Port", "Cmd", "Path", "UserId", "UserIp", "Username",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
