// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-server.proto

package com.y4d.git.server;

public final class GitServerProto {
  private GitServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GitServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.y4d.git.server.GitServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 100;</code>
     * @return The response.
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 100;</code>
     * @return The bytes for response.
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    /**
     * <code>bool success = 101;</code>
     * @return The success.
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code com.y4d.git.server.GitServer}
   */
  public static final class GitServer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.y4d.git.server.GitServer)
      GitServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GitServer.newBuilder() to construct.
    private GitServer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GitServer() {
      response_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GitServer();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.y4d.git.server.GitServerProto.internal_static_com_y4d_git_server_GitServer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.y4d.git.server.GitServerProto.internal_static_com_y4d_git_server_GitServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.y4d.git.server.GitServerProto.GitServer.class, com.y4d.git.server.GitServerProto.GitServer.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 100;
    @SuppressWarnings("serial")
    private volatile java.lang.Object response_ = "";
    /**
     * <code>string response = 100;</code>
     * @return The response.
     */
    @java.lang.Override
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 100;</code>
     * @return The bytes for response.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 101;
    private boolean success_ = false;
    /**
     * <code>bool success = 101;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(response_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 100, response_);
      }
      if (success_ != false) {
        output.writeBool(101, success_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(response_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, response_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(101, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.y4d.git.server.GitServerProto.GitServer)) {
        return super.equals(obj);
      }
      com.y4d.git.server.GitServerProto.GitServer other = (com.y4d.git.server.GitServerProto.GitServer) obj;

      if (!getResponse()
          .equals(other.getResponse())) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.y4d.git.server.GitServerProto.GitServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.y4d.git.server.GitServerProto.GitServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.y4d.git.server.GitServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.y4d.git.server.GitServer)
        com.y4d.git.server.GitServerProto.GitServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.y4d.git.server.GitServerProto.internal_static_com_y4d_git_server_GitServer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.y4d.git.server.GitServerProto.internal_static_com_y4d_git_server_GitServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.y4d.git.server.GitServerProto.GitServer.class, com.y4d.git.server.GitServerProto.GitServer.Builder.class);
      }

      // Construct using com.y4d.git.server.GitServerProto.GitServer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        response_ = "";
        success_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.y4d.git.server.GitServerProto.internal_static_com_y4d_git_server_GitServer_descriptor;
      }

      @java.lang.Override
      public com.y4d.git.server.GitServerProto.GitServer getDefaultInstanceForType() {
        return com.y4d.git.server.GitServerProto.GitServer.getDefaultInstance();
      }

      @java.lang.Override
      public com.y4d.git.server.GitServerProto.GitServer build() {
        com.y4d.git.server.GitServerProto.GitServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.y4d.git.server.GitServerProto.GitServer buildPartial() {
        com.y4d.git.server.GitServerProto.GitServer result = new com.y4d.git.server.GitServerProto.GitServer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.y4d.git.server.GitServerProto.GitServer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.response_ = response_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.success_ = success_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.y4d.git.server.GitServerProto.GitServer) {
          return mergeFrom((com.y4d.git.server.GitServerProto.GitServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.y4d.git.server.GitServerProto.GitServer other) {
        if (other == com.y4d.git.server.GitServerProto.GitServer.getDefaultInstance()) return this;
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 802: {
                response_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 802
              case 808: {
                success_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 808
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 100;</code>
       * @return The response.
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 100;</code>
       * @return The bytes for response.
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 100;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        response_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 100;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        response_ = getDefaultInstance().getResponse();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string response = 100;</code>
       * @param value The bytes for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        response_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 101;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 101;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.y4d.git.server.GitServer)
    }

    // @@protoc_insertion_point(class_scope:com.y4d.git.server.GitServer)
    private static final com.y4d.git.server.GitServerProto.GitServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.y4d.git.server.GitServerProto.GitServer();
    }

    public static com.y4d.git.server.GitServerProto.GitServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GitServer>
        PARSER = new com.google.protobuf.AbstractParser<GitServer>() {
      @java.lang.Override
      public GitServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GitServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GitServer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.y4d.git.server.GitServerProto.GitServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_y4d_git_server_GitServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_y4d_git_server_GitServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020git-server.proto\022\022com.y4d.git.server\"." +
      "\n\tGitServer\022\020\n\010response\030d \001(\t\022\017\n\007success" +
      "\030e \001(\010B\020B\016GitServerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_y4d_git_server_GitServer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_y4d_git_server_GitServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_y4d_git_server_GitServer_descriptor,
        new java.lang.String[] { "Response", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
